color: null
description: null
fieldLayouts:
  f4d2f3a0-b1fd-41db-8f85-100ea9fda68d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-06T20:06:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e9ca43bc-46d7-4e81-894a-292f7281b5ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T20:13:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ee8ac15-c76e-443b-a1c1-ffc14a31c104 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3b95a88-3c2e-4bc3-bf80-7c1d08c36575
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e3085889-cddc-4a1a-bf4c-56dccf22396b
        userCondition: null
handle: image
hasTitleField: true
icon: null
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
