color: null
description: null
fieldLayouts:
  c0df002c-b6fa-40c0-bb45-8edc7b795e71:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-06T19:56:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c3ca9ac2-e8be-4ebd-9fe3-3f2aa800c4bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T20:08:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ded4e4d0-db35-4503-ace2-265cb528b599 # Text
            handle: summary
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 170e78c7-2624-413b-aadf-c4293102b39d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T20:08:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ee8ac15-c76e-443b-a1c1-ffc14a31c104 # Image
            handle: featureImage
            includeInCards: false
            instructions: null
            label: 'Feature Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2139a9a3-100e-42af-b5b6-e53fa13a5021
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T20:08:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b26559bd-619d-4fc2-aead-365cae1a4d77 # Post Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e48241ef-5e57-4b59-884d-08bf027a18a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T20:08:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db521a39-df28-48ca-bdc3-cc23f2143d5f # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a820d7d6-a527-44d9-afc1-4f2735e1cf99
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3582bca4-e33a-4275-9482-ac09f69c8270
        userCondition: null
handle: post
hasTitleField: true
icon: null
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
