color: null
description: null
fieldLayouts:
  8f11cb7c-3abf-40c9-bb7f-9addfc13bf7b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-07T06:49:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1cf82ff3-3eb1-44ad-af54-12485e40645f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T06:51:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ee8ac15-c76e-443b-a1c1-ffc14a31c104 # Image
            handle: featureImage
            includeInCards: false
            instructions: null
            label: 'Feature Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 721b51d0-829d-4ff9-a0aa-b99e4c2a3475
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T06:51:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 57537d62-fe49-48ed-9155-b0c9da296543 # Project Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d9f73ea-b978-4aad-8d61-2e2372589058
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-08T17:31:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db521a39-df28-48ca-bdc3-cc23f2143d5f # Project Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5505c0e-61ce-4d6a-a8d8-5616ad3d3d84
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3e4a707-ed0a-4a6b-8d82-4e48aa6593a5
        userCondition: null
handle: project
hasTitleField: true
icon: null
name: Project
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
