color: null
description: null
fieldLayouts:
  865864e7-c218-458a-9669-8334c7869106:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-06T20:04:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf63a5c9-c13a-4ee0-b68c-0af8dc47f035
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-06T20:13:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ded4e4d0-db35-4503-ace2-265cb528b599 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41879cca-f85d-4e58-83a0-7e966e2d0c06
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c7a8eb02-ca9f-49f4-bf60-ad844371dc25
        userCondition: null
handle: text
hasTitleField: true
icon: null
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
