columnSuffix: null
handle: postContent
instructions: null
name: 'Post Content'
searchable: true
settings:
  createButtonLabel: 'Add block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 4f1e2e67-be05-427c-98ac-a6a963d18a25 # Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7390d5a6-3a27-4ee3-b450-da8cf1498181 # Image
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
