defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8a74c134-d611-491e-9ecc-f0f58582cc13 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  359773b9-45a8-491e-b4ca-e3bbd917f59e: # crafty project
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
