defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 545e08d8-f7bf-43f5-81c0-f70a9243218c # Post
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  359773b9-45a8-491e-b4ca-e3bbd917f59e: # crafty project
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
